# Metadata for your course

title:          Charlie's Github Learning Lab!
tagline:        It's short and sweet
description:    Following the fully guided example or not

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: my-sparkles-repo
  repo: lab-starter-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Welcome
  body: welcome-text.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Create a new PR
  description: Add your name to the README.md file in your new PR
  event: pull_request.opened
  actions:
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add name to README
  - type: respond
    with: pr-opened.md
                  #
                  # - type:
                  #   option:
